name: 04 - Using Actions
on: push
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Printing Folders
        run: |
          echo $GITHUB_WORKSPACE
          ls $GITHUB_WORKSPACE
