name: 05 - 1 - Event Filters and Activity Types
on:
  pull_request:
    branches:
      - tshah/05-filters-activity-types
    types:
      - opened
      - synchronize
  workflow_dispatch:
jobs:
  echo:
    name: Echo
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: |
          echo "Running whenever a PR is opened or synchronized and base branch is main."
