name: 05 - 2 - Event Filters and Activity Types
on:
  pull_request:
    branches:
      - main
    types:
      - closed
jobs:
  echo:
    name: Echo
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: |
          echo "Running whenever a PR is closed."
